/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.statsig.*;
import java.util.Map;
import java.util.HashMap;

import java.io.File;

public class App {
    public static void main(String[] args) {
        LogToStatsig();
    }

    public static boolean LogToStatsig()
    {
        try
        {
            StatsigOptions options = new StatsigOptions.Builder().setEnvironment("development").build();
            
            // Load environment variables from .env file in the parent directory
            io.github.cdimascio.dotenv.Dotenv dotenv = io.github.cdimascio.dotenv.Dotenv.configure()
                .directory("../../")
                .load();
            String serverKey = dotenv.get("SERVER_KEY");
            Statsig statsig = new Statsig(serverKey, options);

            statsig.initialize().get();

            StatsigUser user = new StatsigUser.Builder().setUserID(System.getenv("USER")).build();

            System.out.println("Checking gate 'new_feature_gate' for user " + user.getUserID());

            boolean allowed = statsig.checkGate(user, "new_feature_gate");

            System.out.println("Gate 'new_feature_gate' is " + (allowed ? "allowed" : "not allowed"));

            statsig.logEvent(user, "app_started", allowed ? "true" : "false", null);

            System.out.println("Logged event 'app_started'");

            statsig.shutdown().get();

            System.out.println("Statsig shutdown complete");

            statsig.OverrideParamStore("", "");

            return true;
        }
        catch (Exception e)
        {
            System.out.println("Error during Statsig operation: " + e.getMessage());
            return false;
        }
    }
}
